# Coursework for EG1007

# First we will import the external library numpy and abbreviate it into np
#By using Numpy we can directly get data from our files
# we can also use the numpy functions to automatically work out the mean , standard deviation and maximum power from our wind turbine power text.
import numpy as np # we imported our external library numpy 
Wind_turbine_data = np.loadtxt("windturbinepower.txt" )
# here we created a new folder  and placed our python file and windturbinepower.txt in the same folder.
# next we are going seperate the 2 columns in our data set into time (Seconds )  and power (Watts) of the wind turbine
Time  = Wind_turbine_data[:,0]
# duplicate the first column of our windturbine data . This is the time in watts of the wind turbine
# we created 2 different arrays from our data set since Question 1 only requires the standard deviation , maximum and minimum for power in watts .
Power = Wind_turbine_data[:,1]
# when focusing on question 1 we are only numpy functions for this array
# by using numpy we can work out the maximum , minimum and standard deviation of power
#Question 1)i
print(f'the maximum power of the wind turbine in watts  is {np.amax(Power)}')
print(f'the mean power of the wind turbine in watts is  {np.mean(Power)}')
print(f'the standard deviation of power in watts is  {np.std(Power)}')
# here we used a formatted  string and this allows us to directly insert our power values in a clean readable manner





#Question 1)ii
# we will import another external library - matplotlib
# this will help us visualise the relationship between time and power of the wind turbine - whether it is a linear, cubic exponential etc
# we use matplotlib as this will help us create our graph and plot our Time and power arrays
# we will use plt as a shortcut and abbreviation for the graph
import matplotlib.pyplot as plt
Figure = plt.figure(1)
plt.plot( Time , Power , linestyle = 'solid', mec='r' , marker ='*' , markersize =1)
# this determines what colour style and the presentation of our graphs. How we want our graph plot to look like
plt.xlabel("Time taken for Wind turbine (seconds)")
# our time array we sliced will be on the x axis since it is the independent variable and influences our power
plt.ylabel("Power(Watts) generated by Wind turbine ")
# label vertical  axis as power
plt.title(" The amount of power(Watts) generated by Wind turbine per second")
plt.show()
# we can envision and visualise their relationship , you must have empty brackets () otherwise the graph will not show
# the graph looks similar to trigonometric graph as it has repeating periods and values





#Question 1)iii - calculating the rate of change of power with time ( numerical diffrentiation)
# this is since we have only been given discrete data points and no equations 
# essentially we wil write a code to find the derivative using a finite difference scheme
# we use a finite difference scheme
# mumerically the change in our x axis ( time) cannot be infinitesimal so it shoud be finite and solution becomes approximates
# therefore we have to define a finite value for the difference
# using a finite difference scheme since it gives us a more accurate numerical approximation  and is easier to calculate
# this is the formula to calculate and find the first derivatives from finite differences
# 
#   improved forward scheme (-f(x+2*h)+4*f(x+h)-3*f(x))/(2*h)
#                        or (-f(x[i+2])+4*f(x[i+1])-3*f(x[i]))/(x[i+2])-x[i])
# this is a higher order of accuracy as our change in time  - increases
# we would use forward scheme when for our intial power ( y axis ) and time (x axis)
# however both forward and backward scheme are generally more inaccurate then central scheme 

#   improved backward scheme (3*f(x)-4*f(x-h)+f(x-2*h))/(2*h)
#                       or (3*f(x[i])-4*f(x[i-1])+f(x[i-2]))/(x[i])-x[i-2])
#
#   improve central scheme (f(x+h)-f(x-h))/(2*h) or (f(x[i+1])-f(x[i-1]))/(x[i+1])-x[i-1])
# first we are using the arrays we created from our imported data - Wind_turbine_data
Time = Wind_turbine_data[:,0] 
# within the differennces formula this would be our time 
Power= Wind_turbine_data[:,1] 
# this would be our x[i] within the equation 
# since we already have created our indidiuval power and time arrays. from question 1 part 1 
# we therefore only need to create an empty array to store our derivative function 
Derivative = np.zeros(len(Power)) 
# essentially here we are creating an empty derivative that is the same lenght as our power
# this is so we can store one derivative value for each power value 
# next we need to calculate the hieght 
# This will be the change in difference of time 
Height = Time[1]- Time[0] 
# now we will create a for loop
# we will be using the for loop - since we have a fixed number of times we want to iterate for dependent on the length of our Power array
for i in range ( 0 , len(Power)): 
# in our for loop our start is at the initial value of Power , and we end at our final value of power 
 if i ==0: # essentially in this scenario we would use forward scheme - since we dont know our previous data points
  Derivative[i]=(-Power[i+2]+4*Power[i+1]-3*Power[i])/(2*Height) # this is our forward scheme formula
 elif i == len(Power)-1: 
 # here this is the last data point in our power array therefore we can only use improved  backward scheme formula 
  Derivative[i] =  (Power[i]*3 -4*Power[i-1]+ Power[i-2]) / (2*Height) # here we used [i-2] this shows our backward value we used
 else: # these are conditional statements. we use else at the end for the rest of the data points in between Power[0] and power[i + 1 ] - we will be using improved central scheme for the rest since it is the most accurate 
  Derivative[i] = (Power[i+1] -Power[i-1]) / (2*Height)

print(f"The rate of change of power in watts  with time in seconds  is {Derivative}")



# question 2)i
import numpy as np # here we are using the external library - numpy as this allows us to obtain our trigonemtric function such as in 
import matplotlib.pyplot as plt # this allows us to plot and visualise my results 

def func(t): # first we start by defining our function 
    return 0.4*np.sin(2*np.pi*t)*np.exp(-0.618*t)

def euler(func, t0, te, s0, nstep): # here we essentially define eulers function and what we require in order to work out horizontal displacment
    dt = (te - t0) / nstep # here we define our step size - this is required for our for loop iteration and tells us how much we move up by 
    ts = np.linspace(t0, te, nstep + 1) # here we are creating equal increment for our x values , essentially we want to start at 0 seconds and end at 1 secondw with equal spaces of 0.1 in between - 0.1 periodically
    h = np.zeros(len(ts)) # here h = our y values which is our horizontal displacement and this essentially wil create / initialise an empty array to store our y values for each x specific x values 
    h[0] = s0 # here we are saying our inital horizontal displacement = 0 and our y value is also equal to 0 
    for i in range( nstep): # in the for loop - we are starting at 0 and ending ay our n  step - so our x value starts at 0 and ends at 0.1 
        h[i+1] = h[i] + func(ts[i]) * dt # here we are specifying our eulers equations
    return ts, h  # essentially we are saying return our function 
# here we are defining our parameters - the values given in the equation
t0 = 0 
te = 1
s0 = 0
nstep = 10


ts, h = euler(func, t0, te, s0, nstep) # we are  now going to generate our eulers function and essentially create our x and y values so we can plot and visualise the values 

plt.plot(ts, h ,linestyle = 'dashed' , marker ='*' , markersize =12)
plt.xlabel( " time of turbine in seconds ")
plt.ylabel (" the horizontal displacement of the wind turbine ")
plt.title("horizontal displacement of the hub per second ")
plt.show()
print("Horizontal displacement at t = 1 s:", h[-1]) 


# question 2 )ii - part 2 how do we determine accuracry and analysis of our answer
# change the time step in order to detemine the accuracy
# change the time step in orde to see how accurate it is
# Horizontal velocity function
def Vh(t):
    return 0.4 * np.sin(2 * np.pi * t) * np.exp(-0.618 * t) #here we are oncemore specifying our  equation 

# Euler method for displacement
def euler_displacement(Vh, x0, t0, t_end, dt):#
    # vh  is our function
    #x0 = initial displacement - horizontal displacmeemtnn

    # t0 = initial time
    # t_end = end time
    t = np.arange(t0, t_end + dt, dt)  # here we are creating evens placed interals using starting at 0 and ending at 1 . our interval is dt which is what we calculate in our prevuous 
    x = np.zeros(len(t))# here we are creatting / initalising an array consisting of zeros to the length og time 
    x[0] = x0
    for i in range(1, len(t)):
        x[i] = x[i-1] + Vh(t[i-1]) * dt # this is our equation to work out eulers methods 
    return t, x

# Different time steps to test accuracy
time_steps = [0.5, 0.1, 0.01] # here we are varying the time steps to see how accurate it is 
x0 = 0
t0 = 0
t_end = 5  # adjust if needed
for dt in time_steps:
    t, x = euler_displacement(Vh, x0, t0, t_end, dt)
    print(f"\nTime step Δt = {dt}")
    print("t (s)   x (m)")
    for ti, xi in zip(t, x):
        print(f"{ti:.2f}   {xi:.4f}")

# as we can see the lower the time step the more accurate the eulers methods is 



#Question 2 )iii - bisection method - code for solving non - linear equations 
# we want to calculate maximum displacment
import numpy as np  # we need to import numpy in order to obtain our sin functions 
import matplotlib.pyplot as plt # so we can plot our graph and visualise our results 

# Displacement function given in the question
def displacement(t): # here we first define our equation again 
    return 0.4 * np.sin(2*np.pi*t) * np.exp(-0.618*t)

# Velocity = derivative of displacement
def velocity(t): # we differentiate and get out velocity displacment 
    return (0.4 * np.exp(-0.618*t) *
            (2*np.pi*np.cos(2*np.pi*t) - 0.618*np.sin(2*np.pi*t)))

# Bisection method # here we are using this method to find out the time during the maximum displacement occurs 
def bisection(f, a, b, tol=1e-6): # tol = how accurate do we want the root - to how many signifcant figures etc 
    fa = f(a)  # both a and b is our initial guesses given in the equuation of 0 and 1 
    fb = f(b)

    if fa * fb > 0:
        raise ValueError("f(a) and f(b) must have opposite signs") # essentially if a and b are less then 0 one must be negative the other is a positive  - we exit the bisection method and loop if a and b create a value >0

    while abs(b - a) > tol: # abs = absolute value and we are saying distance between a and b ignoring whether the sign is positive or negative. so keep iterating until the distance of b-a is less then the total 
        c = (a + b) / 2 # c = our midpoint and we define our function 
        fc = f(c)

        if fa * fc < 0: # if our midpoint is greater then 0
            b, fb = c, fc # we swap b with c since c is closer to the maximum displacement
        else:
            a, fa = c, fc # we replace c with a if a multiplied by c is less then 0 

    return (a + b) / 2 #otherwirse we take our midpoint as our root 


# Find time of maximum displacement
t_max = bisection(velocity, 0, 1) # here we are creating our x values - normally how we calculate our x values  
y_max = displacement(t_max) # oncemore initialising an array and how we are going to store rt

print(f"Maximum displacement occurs at t = {t_max:.4f} s")
print(f"Maximum displacement = {y_max:.4f}")

# Plot results
t_vals = np.linspace(0, 2, 400) # here we are stating the time intervals and how evenly we want them spaces from 0 to 2 secomds - since range will go from 0 to 1 
y_vals = displacement(t_vals) # this is our horizontal displacement and how we specify 
# we are plotting a graph to see how accurate our approximation is 
plt.plot(t_vals, y_vals, label="Exact solution")
plt.plot(t_max, y_max, 'ro', label="Maximum displacement")

plt.xlabel("Time (seconds)")
plt.ylabel("Horizontal displacement of wind turbine ")
plt.title("Horizontal displacement of the wind turbine")
plt.legend()
plt.show()
